// Savanna Springs — Service-area (city) page data. Real localized copy from the brief.
window.SS_CITIES = {
  Youngstown: {
    key: 'Youngstown', city: 'Youngstown', county: 'Mahoning', zip: '44512', type: 'municipal',
    h1: 'Water Softeners & Water Treatment in Youngstown, OH',
    lead: 'Hard water, rust stains, or a chlorine taste at your Youngstown tap? Savanna Springs has been the Valley\u2019s local water team since 2008 — free in-home test, right-sized system, professional install.',
    context: 'Most Youngstown homes are on city water from the Mahoning Valley Sanitary District, drawn from Meander Reservoir — treated and chlorinated, so many notice a chlorine taste and switch to RO and whole-house carbon filtration. Older East- and West-side homes pick up taste and staining from aging plumbing, and some outskirts run on wells with hardness and iron.',
    mostCommon: ['Chlorine taste & smell', 'Scale & spotting', 'RO drinking water', 'Aging-plumbing taste'],
    problems: ['Chlorine', 'HardWater', 'Taste', 'Rust', 'Sediment', 'Well'],
    nearby: ['Boardman', 'Austintown', 'Struthers', 'Campbell', 'Poland'],
    meta: 'Water Softeners Youngstown, OH | Savanna Springs',
  },
  Boardman: {
    key: 'Boardman', city: 'Boardman', county: 'Mahoning', zip: '44512', type: 'municipal',
    h1: 'Water Softeners & Water Treatment in Boardman, OH',
    lead: 'Spot-free dishes, softer water, and better-tasting drinking water for your Boardman home — diagnosed with a free test and installed by your local team since 2008.',
    context: 'One of the Valley\u2019s largest suburbs, Boardman is mostly on municipal water. Treated water still leaves scale and a chlorine taste, so most homes add a softener plus an RO system. We size to your exact water and offer financing to make it easy.',
    mostCommon: ['Scale & spotting', 'Chlorine taste', 'RO drinking water', 'Whole-house filtration'],
    problems: ['Chlorine', 'HardWater', 'Taste', 'Sediment', 'Rust', 'SoftWaterOut'],
    nearby: ['Youngstown', 'Poland', 'Canfield', 'Struthers'],
    meta: 'Water Softeners Boardman, OH | Savanna Springs',
  },
  Poland: {
    key: 'Poland', city: 'Poland', county: 'Mahoning', zip: '44514', type: 'mixed',
    h1: 'Water Softeners & Water Treatment in Poland, OH',
    lead: 'Village or township, city water or a private well — Poland homes get the right water solution from Savanna Springs, starting with a free in-home test.',
    context: 'The village runs on municipal water, while many Poland Township homes are on wells with hardness, iron, and sulfur odor. Village homes deal with chlorine taste and scale; township homes face well chemistry. A free test tells us exactly which side you\u2019re on.',
    mostCommon: ['Well hardness / iron / sulfur', 'Rotten-egg odor', 'Chlorine taste (village)', 'RO drinking water'],
    problems: ['Well', 'Smelly', 'HardWater', 'Chlorine', 'Rust', 'Taste'],
    nearby: ['Boardman', 'Struthers', 'New Middletown', 'Youngstown'],
    meta: 'Water Softeners Poland, OH | Savanna Springs',
  },
  Canfield: {
    key: 'Canfield', city: 'Canfield', county: 'Mahoning', zip: '44406', type: 'well',
    h1: 'Well Water Treatment & Softeners in Canfield, OH',
    lead: 'Canfield and Canfield Township are well-water country. We\u2019re well-water specialists — softening, iron removal, and odor control, all backed by a free in-home test.',
    context: 'Lots of private wells here, with hard water carrying iron, manganese, and sulfur that cause staining and rotten-egg odor. The self-sanitizing Sanitizer Plus with Crystal-Right® softens, removes iron and manganese, controls odor, and corrects low pH in one unit — no chemicals to buy.',
    mostCommon: ['Well hardness', 'Iron / manganese staining', 'Rotten-egg odor', 'Low pH'],
    problems: ['Well', 'Smelly', 'Rust', 'HardWater', 'Sediment', 'Taste'],
    nearby: ['Boardman', 'Austintown', 'North Lima', 'South Range'],
    meta: 'Well Water Treatment & Softeners Canfield, OH | Savanna Springs',
  },
  Struthers: {
    key: 'Struthers', city: 'Struthers', county: 'Mahoning', zip: '44471', type: 'municipal',
    h1: 'Water Softeners & Water Treatment in Struthers, OH',
    lead: 'Hard-water scale, an old softener that quit, or a chlorine taste in Struthers? We install new systems and service every brand — book a free water test.',
    context: 'An older river town on municipal water, Struthers sees hard-water scale, chlorine taste, and aging softeners installed by other companies. We service all makes and models, and we\u2019re just minutes away in Lowellville.',
    mostCommon: ['Hard-water scale', 'Chlorine taste', 'Aging / failed softeners', 'RO drinking water'],
    problems: ['HardWater', 'Chlorine', 'SoftWaterOut', 'Taste', 'Rust', 'Sediment'],
    nearby: ['Youngstown', 'Campbell', 'Poland', 'Lowellville'],
    meta: 'Water Softeners Struthers, OH | Savanna Springs',
  },
  Lowellville: {
    key: 'Lowellville', city: 'Lowellville', county: 'Mahoning', zip: '44436', type: 'mixed', hometown: true,
    h1: 'Water Softeners & Water Treatment in Lowellville, OH',
    lead: 'Lowellville is our hometown — our shop is right on River Road. Nobody knows this village\u2019s water better, and nobody gets to you faster. Free water test, always.',
    context: 'Our home base, right by the Pennsylvania line. Whether you\u2019re on municipal water or a private well, we test free and fix it fast — softening, iron and odor removal, or reverse osmosis for drinking water.',
    mostCommon: ['Hardness & scale', 'Iron & sulfur (wells)', 'Fast local service', 'RO drinking water'],
    problems: ['HardWater', 'Smelly', 'Rust', 'Chlorine', 'Taste', 'SoftWaterOut'],
    nearby: ['Struthers', 'Poland', 'Coitsville', 'New Middletown'],
    meta: 'Water Softeners Lowellville, OH | Savanna Springs',
  },
  Austintown: {
    key: 'Austintown', city: 'Austintown', county: 'Mahoning', zip: '44515', type: 'municipal',
    h1: 'Water Softeners & Water Treatment in Austintown, OH',
    lead: 'Soft, spot-free water and better-tasting drinking water for your Austintown home — sized to your water and installed by your local team since 2008.',
    context: 'A large township on Meander Reservoir water, Austintown\u2019s treated supply still leaves scale and a chlorine taste, so most homes pair a softener with an RO system for the best of both.',
    mostCommon: ['Scale & spotting', 'Chlorine taste', 'RO drinking water', 'Whole-house filtration'],
    problems: ['Chlorine', 'HardWater', 'Taste', 'Sediment', 'Rust', 'SoftWaterOut'],
    nearby: ['Youngstown', 'Canfield', 'Boardman', 'Mineral Ridge'],
    meta: 'Water Softeners Austintown, OH | Savanna Springs',
  },
  Salem: {
    key: 'Salem', city: 'Salem', county: 'Columbiana', zip: '44460', type: 'mixed',
    h1: 'Water Softeners & Well Water Treatment in Salem, OH',
    lead: 'In Salem and the Columbiana County countryside, city homes and rural wells need very different treatment. We do both — starting with a free in-home water test.',
    context: 'City homes are on the municipal supply, while the surrounding countryside is heavily on wells with hardness, iron, and sulfur odor. We bring softening and iron/sulfur filtration to the wells, and RO to the city homes.',
    mostCommon: ['Well hardness / iron / sulfur', 'Rotten-egg odor', 'Chlorine taste (in town)', 'RO drinking water'],
    problems: ['Well', 'Smelly', 'HardWater', 'Chlorine', 'Rust', 'Taste'],
    nearby: ['Columbiana', 'Leetonia', 'Canfield', 'Beloit'],
    meta: 'Water Softeners & Well Water Treatment Salem, OH | Savanna Springs',
  },
  SouthRange: {
    key: 'SouthRange', city: 'South Range / North Lima', county: 'Mahoning', zip: '44452', type: 'well',
    h1: 'Well Water Treatment in South Range / North Lima, OH',
    lead: 'The South Range area — North Lima, Greenford, and the surrounding countryside — is private-well country, and that\u2019s exactly where we specialize.',
    context: 'Covering North Lima, Greenford, and the rural Beaver and Green Township countryside, almost everyone here is on a private well. Water is typically hard with iron, manganese, sulfur (rotten-egg), sediment, and low pH. One self-sanitizing Sanitizer Plus softens, removes iron, kills odor, and corrects pH all at once.',
    mostCommon: ['Well hardness', 'Iron / manganese staining', 'Rotten-egg sulfur odor', 'Sediment & low pH'],
    problems: ['Well', 'Smelly', 'Rust', 'HardWater', 'Sediment', 'Chlorine'],
    nearby: ['North Lima', 'Greenford', 'Canfield', 'Poland', 'New Middletown'],
    meta: 'Well Water Treatment — South Range / North Lima, OH | Savanna Springs',
  },
};

window.SS_CITY_ORDER = ['Youngstown', 'Boardman', 'Poland', 'Canfield', 'Struthers', 'Lowellville', 'Austintown', 'Salem', 'SouthRange'];

// product services to surface per city type
window.SS_CITY_SERVICES = {
  municipal: ['Softeners', 'RO', 'WholeHouse', 'Salt'],
  well: ['IronSulfur', 'Softeners', 'WholeHouse', 'RO'],
  mixed: ['Softeners', 'IronSulfur', 'RO', 'Salt'],
};
