// Savanna Springs — Product page data (8 products). Real copy from the build brief.
window.SS_PRODUCTS = {
  Softeners: {
    key: 'Softeners', label: 'Water softeners', icon: 'droplet', color: 'water',
    eyebrow: 'Products · Softeners',
    h1: 'Water softeners that last.',
    lead: 'Highly efficient, demand-based softeners — custom-sized and competitively priced to end hard-water problems throughout your home.',
    models: [
      { name: 'Impression Plus Series®', tag: 'Most popular', blurb: 'Our flagship softener — microprocessor controls with an LED display, meter-based regeneration, and a valve built to never rust.',
        features: ['Microprocessor controls + LED display', 'Meter-based regeneration', 'Chlorine-resistant high-capacity resin', 'NORYL® valve — no screws or bolts to rust', 'Vortech® tank technology'],
        warranty: '20-yr mineral tank · 20-yr resin · 5-yr brine tank · 5-yr control valve · 5-yr labor' },
      { name: 'Impression Plus RC (Resin/Carbon) Series', tag: 'For city water', blurb: 'Removes chlorine and hardness in one tank for municipal water — carbon protects the resin and your plumbing.',
        features: ['Chlorine + hardness in one tank', 'Carbon protects the resin', 'Space-saving single-tank design', 'Ideal for city water'] },
      { name: 'Impression Plus Crystal-Right/Carbon Series', tag: 'For chloramine', blurb: 'Softens while removing chloramine, ammonia, and unwanted odor and taste.',
        features: ['Removes chloramine + ammonia', 'Controls odor & taste', 'Softens at the same time'] },
      { name: 'Impression Plus Twin System', tag: '24-hour soft water', blurb: 'Continuous, around-the-clock soft water for larger households that never want to run out.',
        features: ['Never run out of soft water', '20,000–120,000 grains', 'Up to 28 GPM', 'Sized for big homes'] },
    ],
    highlights: { eyebrow: 'Eco-friendly · Money-saving', title: 'Good for your home and your wallet',
      items: ['Laundry detergent down up to 50%', 'Dish detergent down up to 70%', 'Water-heater efficiency up to 47%', 'Up to 60% less salt than time-clock units', 'Up to 75% less regeneration water'] },
    solves: ['HardWater', 'Chlorine', 'SoftWaterOut'],
    cta: 'Get a free water test and the right-sized softener',
    meta: 'Water Softeners — Impression Plus Series | Savanna Springs',
  },
  RO: {
    key: 'RO', label: 'Reverse osmosis', icon: 'beaker', color: 'navy',
    eyebrow: 'Products · Drinking water',
    h1: 'Bottle-quality drinking water from your own tap.',
    lead: 'Crisp, clean drinking water under your sink — better coffee, clearer ice, and no more hauling cases of bottled water.',
    models: [
      { name: 'Impression Series R.O.', tag: 'Four-stage', blurb: 'Four-stage filtration with a final carbon polish for sparkling, great-tasting water.',
        features: ['Four stages + carbon polish', 'Sparkling, great-tasting water', 'Better coffee & clearer ice', '3-gallon storage tank'],
        warranty: '5-yr warranty · 1-yr labor' },
      { name: 'Eclipse R.O.', tag: 'Top of line', blurb: 'Our best drinking-water system — with a TDS faucet monitor and no-mess filter changes.',
        features: ['TDS faucet monitor', 'Clean drop-in filter changes', 'No electricity needed', '3-gallon storage tank'],
        warranty: '5-yr warranty · 1-yr labor' },
      { name: 'Viqua® UV Sterilization', tag: 'Bacteria protection', blurb: 'Adds a layer of protection against bacteria, viruses, and waterborne pathogens.',
        features: ['Kills bacteria, viruses, algae & mold', 'Guards against crypto & giardia', 'Stainless-steel chamber', 'Lamp-failure alarm'] },
    ],
    highlights: { eyebrow: 'The value', title: 'Bottle-quality for pennies a day',
      items: ['Replaces the bottled-water habit', 'Crisp water straight from the tap', 'Better coffee, tea & ice', 'Rentals available'] },
    solves: ['Taste', 'Chlorine'],
    cta: 'Find the right system with a free water test',
    meta: 'Reverse Osmosis Drinking Water — Impression & Eclipse R.O. | Savanna Springs',
  },
  IronSulfur: {
    key: 'IronSulfur', label: 'Iron & sulfur filters', icon: 'flame', color: 'orange',
    eyebrow: 'Products · Iron & sulfur',
    h1: 'Clear out iron, sulfur, and the rotten-egg smell.',
    lead: 'The toughest well-water problems — iron staining and that rotten-egg odor — solved at the source with self-sanitizing media.',
    models: [
      { name: 'Sanitizer Plus Series with Crystal-Right®', tag: '4-in-1, self-sanitizing', blurb: 'Patented self-chlorinating technology kills iron and sulfur bacteria, then rinses clean — performing like four units in one.',
        features: ['Patented self-chlorinating media', '4-in-1: soften, iron, odor, pH', 'No chemicals to buy', '"Check salt" indicator', 'Lithium battery backup'],
        warranty: '20-yr mineral tank · 20-yr resin · 20-yr Crystal-Right® media · 5-yr control valve · 5-yr labor' },
      { name: 'Impression Plus Filter Series (IMPBF)', tag: 'Custom media', blurb: 'Custom media built to your water — turbidity, chlorine, acidic-water neutralizing, or iron removal.',
        features: ['Turbidity removal', 'Chlorine removal', 'Neutralizing acidic water', 'Iron removal'] },
    ],
    solves: ['Smelly', 'Rust', 'Well'],
    cta: 'Book a free water test — we\u2019ll spec the right media',
    meta: 'Iron & Sulfur Filters — Sanitizer Plus with Crystal-Right | Savanna Springs',
  },
  WholeHouse: {
    key: 'WholeHouse', label: 'Whole-house filtration', icon: 'shield', color: 'water',
    eyebrow: 'Products · Whole-house',
    h1: 'Cleaner, safer water at every tap.',
    lead: 'Custom-designed media systems that treat one problem or several at once — used alongside a conditioner or on their own.',
    models: [
      { name: 'Impression Plus Filter Series (IMPBF)', tag: 'Custom media', blurb: 'Custom-designed media blends that treat one or several problems at once. Use it with a conditioner or alone.',
        features: ['Turbidity removal', 'Chlorine removal', 'Neutralizing acidic water', 'Iron removal'] },
    ],
    highlights: { eyebrow: 'How we design it', title: 'Built around your water, not a catalog',
      items: ['We test your water in-home', 'We determine the media formula', 'We recommend the configuration', 'One or several problems, one system'] },
    solves: ['Sediment', 'Rust', 'Chlorine'],
    cta: 'Get a free water test to design your whole-house system',
    meta: 'Whole-House Water Filtration | Custom Media Systems | Savanna Springs',
  },
  Commercial: {
    key: 'Commercial', label: 'Commercial water treatment', icon: 'factory', color: 'navy',
    eyebrow: 'Products · Commercial',
    h1: 'Reliable, cost-effective commercial water treatment.',
    lead: 'For apartment buildings, nursing homes, restaurants, manufacturing, pharmaceutical operations, and larger homes that need commercial-grade equipment.',
    intro: 'One size doesn\u2019t fit all. We design the system around your project and service it long after install — so your water keeps performing.',
    segments: { eyebrow: 'Who we serve', title: 'Commercial-grade, custom-built',
      items: ['Apartment buildings', 'Nursing homes', 'Restaurants', 'Manufacturing', 'Pharmaceutical', 'Larger homes'] },
    callFirst: true,
    cta: 'Talk through your commercial project',
    meta: 'Commercial Water Treatment Systems | Youngstown, OH | Savanna Springs',
  },
  Bottled: {
    key: 'Bottled', label: 'Bottled water & coolers', icon: 'drop2', color: 'sun',
    eyebrow: 'Products · Delivery',
    h1: 'Premium bottled water & coolers, delivered.',
    lead: 'Premium drinking water from a natural artesian spring in Lowellville, then rigorously filtered — we don\u2019t start with tap water like many competitors.',
    chips: ['20 oz', '1 gallon', '5 gallon'],
    models: [
      { name: '"Glacier" WaterSafe Cooler', tag: 'Top-load', blurb: 'Spill-proof and hygienically sealed, with Dry Guard protection.', features: ['Spill-proof design', 'Hygienically sealed', 'Dry Guard protection'] },
      { name: '"Storm" Back-Saver Cooler', tag: 'Bottom-load', blurb: 'Bottom-loading means no overhead lifting — hot and cold on tap.', features: ['No overhead lifting', 'Bottom-load bottle', 'Hot & cold water'] },
      { name: '"Glacier" Bottle-Less Cooler', tag: 'Bottle-less', blurb: 'Unlimited water with an advanced filter that removes rust, chlorine, lead, cysts, and odors.', features: ['Unlimited water', 'Removes rust, chlorine & lead', 'Filters cysts & odors'] },
      { name: '"Crystal Pro" Bottle-Less Dispenser', tag: 'Bottle-less', blurb: 'UV-protected with hot, ambient, and cold water, 4.7-gallon capacity, and leak detection.', features: ['UV protection', 'Hot / ambient / cold', '4.7-gallon capacity', 'Leak detection'] },
    ],
    delivery: { title: 'Delivery that fits your routine', body: 'Businesses every 1–4 weeks; residential customers get email reminders and just leave empties out. Serving Mahoning, Columbiana & Trumbull counties plus Western PA.' },
    cta: 'Set up delivery — fill out the form or call',
    meta: 'Bottled Water Delivery & Water Coolers | Mahoning Valley | Savanna Springs',
  },
  Salt: {
    key: 'Salt', label: 'Salt delivery', icon: 'truck', color: 'sun',
    eyebrow: 'Products · Salt delivery',
    h1: 'Salt delivery — the better way.',
    lead: 'Salt is heavy, messy, and bulky. Let us handle it. We deliver Pro\u2019s Pick Dura-Cube® and load it for you — so you never lift another bag.',
    highlights: { eyebrow: 'Pro\u2019s Pick Dura-Cube®', title: 'A cleaner, easier salt',
      items: ['Up to 99.8% pure', 'Virtually 100% soluble', 'Compacted to prevent mushing & bridging', '2-handle 40-lb easy-open bag', 'Bag is 50% recycled'] },
    delivery: { title: 'We do the heavy lifting', body: 'Weekly delivery routes across the Valley. We\u2019ll fill your brine tank and stack the bags wherever you want them.' },
    solves: ['SoftWaterOut'],
    cta: 'Set up your salt delivery schedule today',
    meta: 'Water Softener Salt Delivery — Dura-Cube | Savanna Springs',
  },
  Rentals: {
    key: 'Rentals', label: 'Equipment rentals', icon: 'calendar', color: 'water',
    eyebrow: 'Products · Rentals',
    h1: 'Try soft water without the upfront cost.',
    lead: 'Not ready to buy? Rent a softener or drinking-water system and feel the difference first — with a special offer to get you started.',
    models: [
      { name: 'Impression Plus® softener rental', tag: 'One month free', blurb: 'Rent our flagship softener and get one month of free rent to start.', features: ['One month free rent', 'One-year lease', 'Install charge applies', 'Service included'] },
      { name: 'Impression Series R.O. rental', tag: 'Pennies a day', blurb: 'Bottle-quality drinking water for pennies a day — one month free for a limited time.', features: ['One month free (limited time)', 'One-year lease', 'Install charge applies', 'Maintenance included'] },
    ],
    solves: ['HardWater', 'Taste'],
    cta: 'Ask about rentals on your free water test',
    meta: 'Water Softener & R.O. Rentals | Savanna Springs',
  },
};

window.SS_PRODUCT_ORDER = ['Softeners', 'RO', 'IronSulfur', 'WholeHouse', 'Commercial', 'Bottled', 'Salt', 'Rentals'];
window.SS_PRODUCT_BLURB = {
  Softeners: 'Impression Plus® softeners end hard-water scale, spots and dry skin.',
  RO: 'Bottle-quality reverse-osmosis drinking water from your own tap.',
  IronSulfur: 'Self-sanitizing media clears iron, sulfur and the rotten-egg smell.',
  WholeHouse: 'Custom media systems for cleaner, safer water at every tap.',
  Commercial: 'Commercial-grade systems custom-built around your project.',
  Bottled: 'Spring water, coolers and delivery for home and business.',
  Salt: 'We deliver and load Dura-Cube® softener salt — free of the hassle.',
  Rentals: 'Try soft water or RO with no upfront cost — one month free.',
};
