// Savanna Springs — Problem page data (all 8). Real copy from the build brief.
window.SS_PROBLEMS = {
  Smelly: {
    key: 'Smelly', label: 'Rotten-egg smell', icon: 'wind', color: 'sun',
    eyebrow: 'Water problem · Odor',
    h1: 'Why does my water smell like rotten eggs?',
    lead: 'Turn on the faucet and get hit with the smell of rotten eggs — in your drinking water, the shower, or the laundry. Usually not harmful, but unpleasant enough to make you avoid your own tap.',
    problem: 'The smell shows up in drinking water, the shower, and laundry. It\u2019s usually not harmful — just unpleasant enough that you start avoiding it.',
    cause: 'Hydrogen sulfide gas, often from iron and sulfur bacteria in the water or water heater. Those bacteria can also leave a dark "slime" inside fixtures and toilet tanks.',
    steps: [
      { label: 'We diagnose', icon: 'search', body: 'A free in-home water test shows whether it\u2019s hydrogen sulfide, iron/sulfur bacteria, or both.' },
      { label: 'We recommend', icon: 'clipboard', body: 'A Sanitizer Plus conditioner that kills the odor-causing bacteria and softens at the same time — no chemicals to buy.' },
      { label: 'We install', icon: 'wrench', body: 'Sized and installed by our Ohio EPA-licensed team, then serviced for the long haul.' },
    ],
    recommend: 'The Sanitizer Plus Series conditioner with Crystal-Right® media uses patented self-chlorinating technology to kill the odor-causing bacteria, then rinses clean — while softening, removing iron and manganese, and raising low pH in one unit. No chemicals to buy.',
    product: { name: 'Sanitizer Plus with Crystal-Right®', key: 'IronSulfur', badges: ['Made in USA', 'Self-sanitizing', '4-in-1'] },
    cta: 'Stop holding your breath at the tap',
    related: ['Well', 'Rust', 'HardWater'],
    meta: 'Rotten-Egg Smell in Your Water? We Fix It | Savanna Springs',
  },
  HardWater: {
    key: 'HardWater', label: 'Hard water & scale', icon: 'droplet', color: 'water',
    eyebrow: 'Water problem · Hard water',
    h1: 'Hard water is quietly costing you money',
    lead: 'Spotty dishes, crusty faucets, stiff laundry, dry skin and dull hair, and far too much soap. Hard water works against you in every room — and quietly shortens the life of your appliances.',
    problem: 'Spotty dishes, crusty faucets, stiff laundry, dry skin and dull hair, and using too much soap and detergent to get anything clean.',
    cause: 'Excess calcium, magnesium, and sometimes iron leave scale that clogs pipes, shortens water-heater life, and fights every detergent you own.',
    steps: [
      { label: 'We diagnose', icon: 'search', body: 'A free test measures your exact hardness (grains per gallon) and iron, so the system is sized precisely to your water.' },
      { label: 'We recommend', icon: 'clipboard', body: 'A high-efficiency Impression Plus® softener — or the RC Series on city water to remove chlorine and hardness in one tank.' },
      { label: 'We install', icon: 'wrench', body: 'Professionally installed and serviced. Rental and financing available if you\u2019d rather spread the cost.' },
    ],
    recommend: 'The Impression Plus Series® softener uses meter-based regeneration and high-capacity resin — up to 60% less salt and 75% less regeneration water than old time-clock units. On city water, the Impression Plus RC (Resin/Carbon) Series removes chlorine and hardness in one tank.',
    product: { name: 'Impression Plus Series® softeners', key: 'Softeners', badges: ['Made in USA', 'Eco-Friendly', '60% less salt'] },
    payoff: { title: 'The payoff', stats: [['50%', 'less laundry detergent'], ['70%', 'less dish detergent'], ['47%', 'better water-heater efficiency']] },
    cta: 'See what soft water actually feels like',
    related: ['Taste', 'Chlorine', 'SoftWaterOut'],
    meta: 'Hard Water Treatment & Water Softeners | Youngstown OH',
  },
  Rust: {
    key: 'Rust', label: 'Rust & orange stains', icon: 'flame', color: 'orange',
    eyebrow: 'Water problem · Staining',
    h1: 'Stop rust and orange stains for good',
    lead: 'Orange and brown staining in sinks, tubs, toilets, and laundry. A metallic taste. Rust rings that keep coming back no matter how hard you scrub.',
    problem: 'Orange and brown staining in sinks, tubs, toilets and laundry, a metallic taste, and rust rings that keep coming back no matter how often you clean.',
    cause: 'Iron and manganese in your water — which also corrode plumbing and make taste and odor worse over time.',
    steps: [
      { label: 'We diagnose', icon: 'search', body: 'A free test measures iron, manganese, and pH so we can match the right media to your water.' },
      { label: 'We recommend', icon: 'clipboard', body: 'An iron-reducing conditioner or a custom filter built with the right media for your iron levels.' },
      { label: 'We install', icon: 'wrench', body: 'Sized to your water, installed by our team, and serviced on all makes and models.' },
    ],
    recommend: 'An iron-reducing Sanitizer Plus conditioner or a custom Impression Plus Filter Series (IMPBF) built with the right media. For heavy well iron paired with odor, the self-sanitizing Sanitizer Plus handles it all together — softening, iron/manganese removal, and odor control in one unit.',
    product: { name: 'Iron & sulfur filtration', key: 'IronSulfur', badges: ['Made in USA', 'Custom media', 'All makes serviced'] },
    cta: 'Reclaim your white sinks',
    related: ['Smelly', 'Well', 'Sediment'],
    meta: 'Stop Rust & Orange Water Stains | Iron Filtration | Savanna Springs',
  },
  Taste: {
    key: 'Taste', label: 'Bad-tasting water', icon: 'beaker', color: 'navy',
    eyebrow: 'Water problem · Taste',
    h1: 'Better-tasting water, straight from your tap',
    lead: 'A metallic, chemical, or just "off" taste. Cloudy ice. And a recurring bill for bottled water you shouldn\u2019t need to buy in the first place.',
    problem: 'A metallic, chemical or "off" taste, cloudy ice, and the constant expense and hassle of buying bottled water.',
    cause: 'Chlorine, dissolved minerals, and other contaminants. Sometimes water that\u2019s perfectly "safe" still tastes bad because of dissolved solids.',
    steps: [
      { label: 'We diagnose', icon: 'search', body: 'A free test — including a TDS reading — shows exactly what\u2019s affecting the taste of your water.' },
      { label: 'We recommend', icon: 'clipboard', body: 'A reverse-osmosis system under the sink for sparkling drinking water, better coffee, and clearer ice.' },
      { label: 'We install', icon: 'wrench', body: 'Installed and maintained by Savanna Springs. Rentals available for pennies a day.' },
    ],
    recommend: 'A reverse-osmosis system under the sink — the Impression Series R.O. (four-stage + carbon polish) for sparkling water, better coffee and clearer ice. The top-of-line Eclipse R.O. adds a TDS faucet monitor and no-mess filter changes, with no electricity needed. It replaces the bottled-water habit for pennies a day.',
    product: { name: 'Reverse osmosis drinking water', key: 'RO', badges: ['Made in USA', 'Pennies a day', 'TDS monitor'] },
    cta: 'Taste the difference',
    related: ['Chlorine', 'HardWater', 'Sediment'],
    meta: 'Reverse Osmosis Drinking Water Systems | Mahoning Valley',
  },
  Well: {
    key: 'Well', label: 'Well water problems', icon: 'home', color: 'water',
    eyebrow: 'Water problem · Well water',
    h1: 'Well water specialists for Northeast Ohio & Western PA',
    lead: 'Rusty sinks and dishwashers, rotten-egg odor, laundry staining, high lime, sediment, and the occasional bacteria scare. Well water is where many companies struggle — and exactly where we specialize.',
    problem: 'Rusty sinks and dishwashers, rotten-egg odor, laundry staining, high calcium and lime, sediment, and occasional bacteria. It\u2019s where many companies struggle — and where we specialize.',
    cause: 'A changing mix of extreme hardness, iron, manganese, sulfur, low pH, and sediment that varies well to well — and even season to season.',
    steps: [
      { label: 'We diagnose', icon: 'search', body: '35+ years of experience plus the newest media and controls. We test in your home and build around your well\u2019s exact chemistry.' },
      { label: 'We recommend', icon: 'clipboard', body: 'Iron-reducing conditioning, self-chlorinating odor control, UV for bacteria, or the right filter/softener combo — whatever your well needs.' },
      { label: 'We install', icon: 'wrench', body: 'Custom-built, professionally installed, and serviced for life.' },
    ],
    recommend: 'Iron-reducing conditioning for rusty fixtures; the self-chlorinating Sanitizer Plus with Crystal-Right® for odor; Viqua® UV for bacteria; and the right filter/softener combo for staining. The Sanitizer Plus performs like four units in one — softening, removing iron and manganese, controlling odor, and raising pH.',
    product: { name: 'Sanitizer Plus & well solutions', key: 'IronSulfur', badges: ['35+ yrs experience', 'Self-sanitizing', 'UV available'] },
    cta: 'Tame your well water',
    related: ['Smelly', 'Rust', 'Sediment'],
    meta: 'Well Water Treatment — Iron, Sulfur & Sediment | NE Ohio',
  },
  Sediment: {
    key: 'Sediment', label: 'Sediment & cloudy water', icon: 'waves', color: 'water',
    eyebrow: 'Water problem · Sediment',
    h1: 'Cloudy, gritty, or discolored water?',
    lead: 'A cloudy glass, grit in your faucet aerators, and tinted water that clogs fixtures and wears out appliances before their time.',
    problem: 'A cloudy glass, grit collecting in aerators, and tinted water that clogs fixtures and shortens the life of your appliances.',
    cause: 'Turbidity from suspended particles and sediment — or acidic (low-pH) water pulling color and metals out of your pipes, which can cause blue-green staining and a metallic taste.',
    steps: [
      { label: 'We diagnose', icon: 'search', body: 'A free test checks turbidity, sediment, and pH/alkalinity to pinpoint what\u2019s clouding your water.' },
      { label: 'We recommend', icon: 'clipboard', body: 'A custom filter for turbidity, plus a neutralizing filter where acidic water is the culprit.' },
      { label: 'We install', icon: 'wrench', body: 'Built to your water and installed by our team.' },
    ],
    recommend: 'A custom Impression Plus Filter Series (IMPBF) for turbidity, plus a neutralizing filter where needed for acidic water. We test in-home, determine the media formula, and build the configuration around what your water actually needs.',
    product: { name: 'Whole-house filtration', key: 'WholeHouse', badges: ['Custom media', 'Made in USA', 'pH neutralizing'] },
    cta: 'Clear it up',
    related: ['Rust', 'Well', 'Taste'],
    meta: 'Cloudy Water, Sediment & Discoloration Treatment | Savanna Springs',
  },
  Chlorine: {
    key: 'Chlorine', label: 'Chlorine taste & smell', icon: 'flask', color: 'sun',
    eyebrow: 'Water problem · Chlorine',
    h1: 'Get the "pool water" smell out of your tap',
    lead: 'City water that smells and tastes like a swimming pool. It\u2019s not harmful — but it\u2019s unpleasant every single day, in every glass and every shower.',
    problem: 'City water that smells or tastes like chlorine. It isn\u2019t harmful, but it\u2019s unpleasant daily — in your drinking water, your coffee, and your shower.',
    cause: 'Municipal chlorine or chloramine. Chloramine in particular can irritate skin, break down rubber plumbing parts, and harm aquarium fish.',
    steps: [
      { label: 'We diagnose', icon: 'search', body: 'A free test confirms whether it\u2019s chlorine or chloramine — which changes the media we use.' },
      { label: 'We recommend', icon: 'clipboard', body: 'A Resin/Carbon softener that removes chlorine and hardness in one tank, or Crystal-Right/Carbon for tougher chloramine.' },
      { label: 'We install', icon: 'wrench', body: 'Sized, installed, and serviced by Savanna Springs.' },
    ],
    recommend: 'The Impression Plus RC (Resin/Carbon) for chlorine plus hardness in one tank; Impression Plus Crystal-Right/Carbon for tougher chloramine and ammonia; or an RO system for drinking water only. A free test tells us which media your city water calls for.',
    product: { name: 'Impression Plus RC & RO', key: 'Softeners', badges: ['Made in USA', 'One-tank design', 'City water'] },
    cta: 'Lose the chlorine taste',
    related: ['Taste', 'HardWater', 'Sediment'],
    meta: 'Remove Chlorine & Chloramine Taste from City Water | Savanna Springs',
  },
  SoftWaterOut: {
    key: 'SoftWaterOut', label: 'Running out of soft water', icon: 'truck', color: 'sun',
    eyebrow: 'Water problem · Salt & capacity',
    h1: 'Tired of hauling salt — or running out of soft water?',
    lead: 'Lugging heavy, messy salt bags down the basement stairs. Or running out of soft water mid-week because the system was never sized right. There\u2019s a better way.',
    problem: 'Lugging heavy, messy salt bags — or running out of soft water mid-week because an undersized system can\u2019t keep up with your household.',
    steps: [
      { label: 'Right-size it', icon: 'search', body: 'We size the system to your household — including Impression Plus Twin Systems for 24-hour soft water (20,000–120,000 grains, up to 28 GPM).' },
      { label: 'Salt delivery', icon: 'truck', body: 'We take salt off your plate with Pro\u2019s Pick Dura-Cube® — we fill the brine tank and stack the bags wherever you want.' },
      { label: 'Weekly routes', icon: 'calendar', body: 'Weekly delivery routes available across the Valley, so you never run out and never lift another bag.' },
    ],
    recommend: 'Right-size the system — including Impression Plus Twin Systems for continuous 24-hour soft water (20,000–120,000 grains, up to 28 GPM) — and let us deliver Pro\u2019s Pick Dura-Cube® softener salt. We\u2019ll fill the brine tank and stack the bags wherever you like.',
    product: { name: 'Salt delivery & Twin Systems', key: 'Salt', badges: ['Free delivery', 'Twin systems', 'Weekly routes'] },
    cta: 'Never run out — or lift another bag',
    related: ['HardWater', 'Well', 'Rust'],
    meta: 'Salt Delivery & Never Run Out of Soft Water | Savanna Springs',
  },
};

// display order for the hub & picker
window.SS_PROBLEM_ORDER = ['Smelly', 'HardWater', 'Rust', 'Taste', 'Well', 'Sediment', 'Chlorine', 'SoftWaterOut'];
window.SS_PROBLEM_BLURB = {
  Smelly: 'That sulfur odor in your tap and shower water.',
  HardWater: 'Spotty dishes, crusty faucets, dry skin, more soap.',
  Rust: 'Stains in sinks, tubs, toilets, and laundry.',
  Taste: 'Cloudy, metallic, or chemical-tasting tap water.',
  Well: 'Iron, sulfur, sediment, and bacteria from a well.',
  Sediment: 'Cloudy, gritty, or discolored water at the tap.',
  Chlorine: 'That "pool water" smell from city water.',
  SoftWaterOut: 'Hauling salt or running out of soft water.',
};
